name: Deploy App with Docker Compose
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Instalar SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Sincronizar repositorios
      run: |
        git config --global user.email "a21bumalu@iesgrancapitan.org"
        git config --global user.name "lugiLB800"
        cd ..
        git clone git@github.com:iesgrancapitan-proyectos/202324asir-junio-DOCKERS_DEVOPS-javilu.git
        cp -rf 202324daw-junio-libreria-andrea-andres/* /home/runner/work/202324daw-junio-libreria-andrea-andres/202324asir-junio-DOCKERS_DEVOPS-javilu/lastversion/
        cd /home/runner/work/202324daw-junio-libreria-andrea-andres/202324asir-junio-DOCKERS_DEVOPS-javilu/lastversion
        git add .
        git diff-index --quiet HEAD || git commit -m "sincronizacion"
        git branch -M main
        git remote set-url origin git@github.com:iesgrancapitan-proyectos/202324asir-junio-DOCKERS_DEVOPS-javilu.git
        git push origin main
        
    - name: Instalar dependencias
      run: |
        cd /home/runner/work/202324daw-junio-libreria-andrea-andres/202324asir-junio-DOCKERS_DEVOPS-javilu/lastversion
        npm install

    - name: Probar el docker
      run: |
        cd /home/runner/work/202324daw-junio-libreria-andrea-andres/202324asir-junio-DOCKERS_DEVOPS-javilu
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d
